export default [
  {
    type: "function",
    name: "createEvent",
    inputs: [
      { name: "_name", type: "string", internalType: "string" },
      { name: "_host", type: "string", internalType: "string" },
      { name: "_venue", type: "string", internalType: "string" },
      { name: "_imageUrl", type: "string", internalType: "string" },
      { name: "_lumaLink", type: "string", internalType: "string" },
      { name: "_time", type: "string", internalType: "string" },
      { name: "_long", type: "string", internalType: "string" },
      { name: "_lat", type: "string", internalType: "string" },
      {
        name: "_stats",
        type: "tuple",
        internalType: "struct Stats",
        components: [
          { name: "overall", type: "int8", internalType: "int8" },
          { name: "food", type: "int8", internalType: "int8" },
          { name: "technical", type: "int8", internalType: "int8" },
          { name: "networking", type: "int8", internalType: "int8" },
          { name: "fun", type: "int8", internalType: "int8" },
          { name: "swag", type: "int8", internalType: "int8" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "events",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "host", type: "string", internalType: "string" },
      { name: "venue", type: "string", internalType: "string" },
      { name: "imageUrl", type: "string", internalType: "string" },
      { name: "lumaLink", type: "string", internalType: "string" },
      { name: "time", type: "string", internalType: "string" },
      { name: "long", type: "string", internalType: "string" },
      { name: "lat", type: "string", internalType: "string" },
      {
        name: "stats",
        type: "tuple",
        internalType: "struct Stats",
        components: [
          { name: "overall", type: "int8", internalType: "int8" },
          { name: "food", type: "int8", internalType: "int8" },
          { name: "technical", type: "int8", internalType: "int8" },
          { name: "networking", type: "int8", internalType: "int8" },
          { name: "fun", type: "int8", internalType: "int8" },
          { name: "swag", type: "int8", internalType: "int8" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllEvents",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct Event[]",
        components: [
          { name: "name", type: "string", internalType: "string" },
          { name: "host", type: "string", internalType: "string" },
          { name: "venue", type: "string", internalType: "string" },
          { name: "imageUrl", type: "string", internalType: "string" },
          { name: "lumaLink", type: "string", internalType: "string" },
          { name: "time", type: "string", internalType: "string" },
          { name: "long", type: "string", internalType: "string" },
          { name: "lat", type: "string", internalType: "string" },
          {
            name: "stats",
            type: "tuple",
            internalType: "struct Stats",
            components: [
              { name: "overall", type: "int8", internalType: "int8" },
              { name: "food", type: "int8", internalType: "int8" },
              { name: "technical", type: "int8", internalType: "int8" },
              { name: "networking", type: "int8", internalType: "int8" },
              { name: "fun", type: "int8", internalType: "int8" },
              { name: "swag", type: "int8", internalType: "int8" },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasRated",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rateEvent",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "overallVote", type: "uint8", internalType: "uint8" },
      { name: "foodVote", type: "uint8", internalType: "uint8" },
      { name: "technicalVote", type: "uint8", internalType: "uint8" },
      { name: "networkingVote", type: "uint8", internalType: "uint8" },
      { name: "funVote", type: "uint8", internalType: "uint8" },
      { name: "swagVote", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUserPref",
    inputs: [{ name: "pref", type: "string", internalType: "string" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userPref",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "verifyAttendance",
    inputs: [
      { name: "eventId", type: "uint256", internalType: "uint256" },
      { name: "user", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
] as const;
